# Generated by Django 5.0.4 on 2026-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('is_verified', False)), fields=['email', '-expires_at'], name='otp_email_expires_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='otpverification',
            constraint=models.CheckConstraint(check=models.Q(('attempts__lte', 5)), name='attempts_limit_check'),
        ),
    ]
