# Generated by Django 5.0.4 on 2026-04-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_officer_user'),
        ('accounts', '0003_otpverification_otpverification_attempts_limit_check'),
    ]

    operations = [
    ]
