# Generated by Django 5.0.4 on 2026-04-11 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('original_value', models.TextField(blank=True, null=True)),
                ('current_value', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('state', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('edited', 'Edited by Staff'), ('flagged', 'Flagged for Re-upload')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_verifications', to='documents.document')),
                ('ocr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.ocrresult')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'state'], name='verificatio_documen_f76d65_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fieldverification',
            constraint=models.UniqueConstraint(fields=('document', 'field_name', 'ocr_result'), name='unique_field_per_ocr_result'),
        ),
    ]
