# Generated by Django 5.0.4 on 2026-04-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_fieldverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldverification',
            name='is_superseded',
            field=models.BooleanField(default=False),
        ),
    ]
