# Generated by Django 5.0.4 on 2026-04-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_rollback_auditlog_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='verificatio_applica_e1ddfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='verificatio_user_id_1055de_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='verificatio_timesta_40f9bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='verification_applicat_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='verification_user_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='verification_timest_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='application',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_value',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='verificatio_entity__1acfcb_idx'),
        ),
    ]
