# Generated by Django 5.0.4 on 2026-04-10 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('students', '0002_pushtoken_pushtoken_uniq_push_token_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_verification', 'Under Verification'), ('verified', 'Verified'), ('seat_allocated', 'Seat Allocated'), ('fee_pending', 'Fee Pending'), ('admitted', 'Admitted'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('branch_preferences', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_quota', models.CharField(blank=True, max_length=20, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_concession', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_paid', models.BooleanField(default=False)),
                ('fee_paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_proof_path', models.CharField(blank=True, max_length=500, null=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.branch')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_applications', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='students.studentprofile')),
            ],
        ),
    ]
