# Generated by Django 5.0.4 on 2026-04-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitted_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
