# Generated by Django 5.0.4 on 2026-04-10 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_label', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('admission_open_date', models.DateField()),
                ('admission_close_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota', models.CharField(choices=[('general', 'General'), ('obc', 'OBC'), ('sc', 'SC'), ('st', 'ST'), ('management', 'Management'), ('nri', 'NRI')], max_length=20)),
                ('total_seats', models.IntegerField()),
                ('allocated_seats', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='uniq_current_academic_year'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.academicyear'),
        ),
        migrations.AddField(
            model_name='seatmatrix',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.branch'),
        ),
        migrations.AddConstraint(
            model_name='seatmatrix',
            constraint=models.UniqueConstraint(fields=('branch', 'academic_year', 'quota'), name='uniq_branch_year_quota'),
        ),
        migrations.AddConstraint(
            model_name='seatmatrix',
            constraint=models.CheckConstraint(check=models.Q(('allocated_seats__lte', models.F('total_seats'))), name='allocated_lte_total_seats'),
        ),
        migrations.AddConstraint(
            model_name='seatmatrix',
            constraint=models.CheckConstraint(check=models.Q(('total_seats__gte', 0)), name='total_seats_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='seatmatrix',
            constraint=models.CheckConstraint(check=models.Q(('allocated_seats__gte', 0)), name='allocated_seats_gte_zero'),
        ),
    ]
