# Generated by Django 5.0.4 on 2026-04-10 09:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('marksheet_10', '10th Marksheet'), ('marksheet_12', '12th Marksheet'), ('rank_card', 'Entrance Rank Card')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mime_type', models.CharField(max_length=50)),
                ('upload_version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('extracted', 'Extracted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='processing', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.studentprofile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField()),
                ('extracted_fields', models.JSONField()),
                ('confidence_scores', models.JSONField()),
                ('overall_confidence', models.FloatField()),
                ('processing_duration_ms', models.IntegerField()),
                ('ocr_version', models.IntegerField()),
                ('llm_model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='documents.document')),
            ],
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('student', 'document_type'), name='unique_doc_per_type_per_student'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('file_size_bytes__lte', 5242880)), name='file_size_limit_check'),
        ),
        migrations.AddConstraint(
            model_name='ocrresult',
            constraint=models.UniqueConstraint(fields=('document', 'ocr_version'), name='unique_ocr_version_per_doc'),
        ),
    ]
