# Generated by Django 5.0.4 on 2026-04-11 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('blurry', 'Blurry Image'), ('wrong_document', 'Wrong Document'), ('incomplete', 'Incomplete Document'), ('expired', 'Expired Document'), ('mismatch', 'Data Mismatch'), ('unreadable', 'Unreadable'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reupload_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='reupload_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
