# Generated by Django 5.0.4 on 2026-04-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_rejected_at_document_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
    ]
